### ISSUE TITLE
Key Hex Codes

### ISSUE THREAD

**Issue by MayaGans** [willdebras/shinykeyboard#1]
So based on shinyBody:

```
 "<svg preserveAspectRatio='none' overflow='auto' class='part head' fill='{data[1]}'.....
```

We need to: 

 1. Give each key a fill={var} so we can glue in the proper hex
 2. Create an R list for each palette

That way we can switch the CSS between palettes

For example 

```
<svg key id="A" fill={group1}>
<svg key id="B" fill={group2}>


colorlist <- list(
  sharla1 = c(group1 = "red",  group2 = "green"),
 sharla2 = c(group1 = "yellow",  group2 = "pink")
)
```

then its fairly easy to apply the right color list based on if the user selects `sharla1` or `sharla2`

Does that make sense @willdebras ?

**Comment by willdebras** [comment]
I added a file called `sharla_colors` that contains three color palettes based on various keyboard colors. It has parameters for the different colors necessary for the keyboard.

I also added an svg file called `keyboard_glue.svg` that has `{}` notation to pipe in all the necessary colors, including the stroke colors and text colors.
