### ISSUE TITLE
Create a keycode map

### ISSUE THREAD

**Issue by MayaGans** [willdebras/shinykeyboard#3]
Translating JavaScript keycodes for letters is easy, but we need a lookup table for the other keys, and it needs to match the ids given in the svg (for instance, the id for delete is "del").

**Comment by MayaGans** [comment]
https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvpin/key-codes-and-key-labels.html

**Comment by willdebras** [comment]
Awesome seems easy enough. Should these be just a list/df of two vectors in R or a JS array? Would it just need to map the key code in this table to a vector of the ids of the keys needed for the multiple input? If you let me know best format for this I can create this mapping today.

**Comment by MayaGans** [comment]
It would be a JS array of all the non-alphabetical keys..... but I'm feeling overwhelmed because: `event.keyCode` returns a different key code for non-alphabetical keys depending on what keyboard you have?!?! 

So we might have to create a map like [I'm making this up entirely]: 

```
keymap = [
 del: {8, 12, 100},
 esc: {43, 24, 33},
 1: {22, 90, 30},
 ......
]
```

but like accounting for every keyboard seems onerous --- that said SOMEONE should have this type of array out there already? Maybe we just do some legwork to not re-invent the wheel first?

**Comment by MayaGans** [comment]
https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes

**Comment by MayaGans** [comment]
I started this in my PR - if you want to finish it up and give the key names the same as the id's (ie "del" not "delete" as current?)

**Comment by willdebras** [comment]
YEP! Can do. I will merge and work on updating with the key names.

**Comment by MayaGans** [comment]
please don't hate me here's an updated list - can you correct these ids please!

```
let keymap = {
  'backspace': 8,
  'tab': 9,
  'enter': 13,
  'shift': 16,
  'ctrl': 17,
  'alt': 18,
  'pause': 19,
  'caps lock': 20,
  'escape': 27,
  'space': 32,
  'page up': 33,
  'page down': 34,
  'end': 35,
  'home': 36,
  'left arrow': 37,
  'up arrow':	38,
  'right arrow':	39,
  'down arrow':	40,
  'insert':	45,
  'delete': 46,
  '0': 48,
  '1': 49,
  '2': 50,
  '3': 51,
  '4': 52,
  '5': 53,
  '6': 54,
  '7': 55,
  '8': 56,
  '9': 57,
  'a': 65,
  'b': 66,
  'c': 67,
  'd': 68,
  'e': 69,
  'f': 70,
  'g': 71,
  'h': 72,
  'i': 73,
  'j': 74,
  'k': 75,
  'l': 76,
  'm': 77,
  'n': 78,
  'o': 79,
  'p': 80,
  'q': 81,
  'r': 82,
  's': 83,
  't': 84,
  'u': 85,
  'v': 86,
  'w': 87,
  'x': 88,
  'y': 89,
  'z': 90,
  'left window key': 91,
  'right window key': 92,
  'select key':	93,
  'numpad 0':	96,
  'numpad 1':	97,
  'numpad 2':	98,
  'numpad 3':	99,
  'numpad 4':	100,
  'numpad 5':	101,
  'numpad 6':	102,
  'numpad 7':	103,
  'numpad 8':	104,
  'numpad 9': 105,
  'multiply': 106,
  'add':	107,
  'subtract':	109,
  'decimal point': 110,
  'divide': 111,
  'f1':	112,
  'f2':	113,
  'f3':	114,
  'f4':	115,
  'f5':	116,
  'f6':	117,
  'f7':	118,
  'f8':	119,
  'f9':	120,
  'f10': 121,
  'f11': 122,
  'f12': 123,
  'num lock': 144,
  'scroll lock': 145,
  'semi-colon': 186,
  'equal sign': 187,
  'comma':	188,
  'dash': 189,
  'period': 190,
  'forward slash': 191,
  'grave accent': 192,
  'open bracket': 219,
  'back slash': 220,
  'close braket': 221,
  'single quote': 222
};
```

This is in the `controlkeys` branch btw...
