### ISSUE TITLE
Adding ID/binding to glyphs?

### ISSUE THREAD

**Issue by willdebras** [willdebras/shinykeyboard#7]
The svg has glyphs to represent the letters/symbols over the top of the keys. Unfortunately if you click on the exact pixels of these glyphs the key no-regs and does not return anything. We might want to add IDs to these to bind them.

Otherwise, we need to remove all of these glyphs and add <text> in the middle of the svg path with a class to size/center it, so it registers with the surrounding path.

**Comment by MayaGans** [comment]
Yeah @willdebras I was wondering about this... I don't know anything about SVGs and I am a CSS 👶 but can we add padding around the glyphs so they cover the whole key?

**Comment by willdebras** [comment]
I _think_ I can figure this out in svg, but we will see. Adding padding in CSS could work.

**Comment by MayaGans** [comment]
I think we can close this now, @willdebras ? It seems to work okay?

**Comment by willdebras** [comment]
Agreed! Closed.
