### ISSUE TITLE
SVG + checkbox positioning

### ISSUE THREAD

**Issue by MayaGans** [willdebras/shinykeyboard#9]
I was hoping you could take a look at this one.... I create a simple checkbox

```
tags$input(id=paste0(inputId, "_switch"),
               class="toggle-button",
               type="checkbox")
```

and cough borrowed this code for css: https://codepen.io/adaltojunior/pen/jOWpXRm [I shoved it all into styles.css] 

but the toggle is MASSIVE and the keyboard covers up the `output$debug`

I was wondering if you'd want to work on making this smaller/practical, I was thinking in the top left corner of the keyboard? 

You have full aesthetic freedom to go wild here, once it's working I'll add it to the backend so when the user switches it all on keys pressed will have the `selected` class added

**Comment by MayaGans** [comment]
The switch should be WAY smaller and I had to add NINE `br()`s so the output is under the keyboard, can we put the keyboard in a container div so it's not ON TOP of other shiny inputs?

**Comment by willdebras** [comment]
Absolutely. I thought I'd have time this weekend to work on this, but can get to it in the AM. It definitely shouldn't overhang like it does. I'll fix both of these shortly.
